project:
  type: website

website:
  title: "Stage Méta-Analyses"
  navbar:
    background: dark
    search: true
    right:
      - icon: github
        href: https://github.com/assiacmyk
      - icon: lightbulb
        href: "#"
  page-navigation: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    code-fold: true

